name: BUKKIT-3371
version: @VERSION@
description: Test plugin
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/bukkit-test/BUKKIT-3371
main: edgruberman.bukkit.bukkit_3371.Main
commands:
  command: